[package]
name = "safercom"
version = "0.1.0"
authors = ["Michael Gawlik <michaelgawlik1983@gmail.com>"]
edition = "2018"

[workspace]

[dependencies]
idl = {path="./idl"}

[[example]]
name = "file_run_dialog"