[package]
name = "idl"
version = "0.1.0"
authors = ["Michael Gawlik <michaelgawlik1983@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = {version="0.15.24", features=["full"]}
quote = "0.6.10"